package page.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BalanceSheetDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BALANCESHEETDETAILS_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "BALANCESHEETDETAILS_ID_GENERATOR", sequenceName = "BALANCESHEETDETAILS_ID_SEQ")
    private java.lang.Long id;

    public BalanceSheetDetails() {
    }
    
    public BalanceSheetDetails(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}