package page.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BlacklistCheck implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BLACKLISTCHECK_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BLACKLISTCHECK_ID_GENERATOR", sequenceName = "BLACKLISTCHECK_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("BlackList Amount")
   private Integer blackListAmount;

   @org.kie.api.definition.type.Label("BlackList Description")
   private java.lang.String blackListDescription;

   @org.kie.api.definition.type.Label("BlackList Type")
   private java.lang.String blackListType;

   public BlacklistCheck()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getBlackListDescription()
   {
      return this.blackListDescription;
   }

   public void setBlackListDescription(java.lang.String blackListDescription)
   {
      this.blackListDescription = blackListDescription;
   }

   public java.lang.String getBlackListType()
   {
      return this.blackListType;
   }

   public void setBlackListType(java.lang.String blackListType)
   {
      this.blackListType = blackListType;
   }

   public java.lang.Integer getBlackListAmount()
   {
      return this.blackListAmount;
   }

   public void setBlackListAmount(java.lang.Integer blackListAmount)
   {
      this.blackListAmount = blackListAmount;
   }

   public BlacklistCheck(java.lang.Long id, java.lang.Integer blackListAmount,
         java.lang.String blackListDescription, java.lang.String blackListType)
   {
      this.id = id;
      this.blackListAmount = blackListAmount;
      this.blackListDescription = blackListDescription;
      this.blackListType = blackListType;
   }

}