package page.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FinancialDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FINANCIALDETAILS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "FINANCIALDETAILS_ID_GENERATOR", sequenceName = "FINANCIALDETAILS_ID_SEQ")
   private java.lang.Long id;

   private java.lang.Long processInstanceID;

   private java.lang.String customerOccupation;

   private Integer month1Salary;

   private Integer month2Salary;

   private Integer month3Salary;

   private Integer monthlyAvgSalary;

   private Integer year2Income;

   private Integer year1Income;

   private Integer year3Income;

   private Integer avgAnnualIncome;

   private Integer otherIncome;

   private Integer existingMonthlyEMI;

   private Integer incomeCreditScore;

   private java.lang.Integer cashAtBank;

   private java.lang.Integer valueOfImmovableProperty;

   private java.lang.Integer valueOfShareAndSecurities;

   private java.lang.Integer fixedDeposits;

   private java.lang.Integer currentBalanceInPf;

   private java.lang.Integer others;

   private java.lang.Integer totalAssests;

   private java.lang.Integer creditSocietyLoan;

   private java.lang.Integer employerLoan;

   private java.lang.Integer homeLoan;

   private java.lang.Integer pfLoan;

   private java.lang.Integer vehicleLoan;

   private java.lang.Integer personalLoan;

   private java.lang.Integer otherLoan;

   private java.lang.Integer creditCard;

   private java.lang.Integer totalLiabilites;

   public FinancialDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Long getProcessInstanceID()
   {
      return this.processInstanceID;
   }

   public void setProcessInstanceID(java.lang.Long processInstanceID)
   {
      this.processInstanceID = processInstanceID;
   }

   public java.lang.String getCustomerOccupation()
   {
      return this.customerOccupation;
   }

   public void setCustomerOccupation(java.lang.String customerOccupation)
   {
      this.customerOccupation = customerOccupation;
   }

   public java.lang.Integer getMonth1Salary()
   {
      return this.month1Salary;
   }

   public void setMonth1Salary(java.lang.Integer month1Salary)
   {
      this.month1Salary = month1Salary;
   }

   public java.lang.Integer getMonth2Salary()
   {
      return this.month2Salary;
   }

   public void setMonth2Salary(java.lang.Integer month2Salary)
   {
      this.month2Salary = month2Salary;
   }

   public java.lang.Integer getMonth3Salary()
   {
      return this.month3Salary;
   }

   public void setMonth3Salary(java.lang.Integer month3Salary)
   {
      this.month3Salary = month3Salary;
   }

   public java.lang.Integer getMonthlyAvgSalary()
   {
      return this.monthlyAvgSalary;
   }

   public void setMonthlyAvgSalary(java.lang.Integer monthlyAvgSalary)
   {
      this.monthlyAvgSalary = monthlyAvgSalary;
   }

   public java.lang.Integer getYear2Income()
   {
      return this.year2Income;
   }

   public void setYear2Income(java.lang.Integer year2Income)
   {
      this.year2Income = year2Income;
   }

   public java.lang.Integer getYear1Income()
   {
      return this.year1Income;
   }

   public void setYear1Income(java.lang.Integer year1Income)
   {
      this.year1Income = year1Income;
   }

   public java.lang.Integer getYear3Income()
   {
      return this.year3Income;
   }

   public void setYear3Income(java.lang.Integer year3Income)
   {
      this.year3Income = year3Income;
   }

   public java.lang.Integer getAvgAnnualIncome()
   {
      return this.avgAnnualIncome;
   }

   public void setAvgAnnualIncome(java.lang.Integer avgAnnualIncome)
   {
      this.avgAnnualIncome = avgAnnualIncome;
   }

   public java.lang.Integer getOtherIncome()
   {
      return this.otherIncome;
   }

   public void setOtherIncome(java.lang.Integer otherIncome)
   {
      this.otherIncome = otherIncome;
   }

   public java.lang.Integer getExistingMonthlyEMI()
   {
      return this.existingMonthlyEMI;
   }

   public void setExistingMonthlyEMI(java.lang.Integer existingMonthlyEMI)
   {
      this.existingMonthlyEMI = existingMonthlyEMI;
   }

   public java.lang.Integer getIncomeCreditScore()
   {
      return this.incomeCreditScore;
   }

   public void setIncomeCreditScore(java.lang.Integer incomeCreditScore)
   {
      this.incomeCreditScore = incomeCreditScore;
   }

   public java.lang.Integer getCashAtBank()
   {
      return this.cashAtBank;
   }

   public void setCashAtBank(java.lang.Integer cashAtBank)
   {
      this.cashAtBank = cashAtBank;
   }

   public java.lang.Integer getValueOfImmovableProperty()
   {
      return this.valueOfImmovableProperty;
   }

   public void setValueOfImmovableProperty(
         java.lang.Integer valueOfImmovableProperty)
   {
      this.valueOfImmovableProperty = valueOfImmovableProperty;
   }

   public java.lang.Integer getValueOfShareAndSecurities()
   {
      return this.valueOfShareAndSecurities;
   }

   public void setValueOfShareAndSecurities(
         java.lang.Integer valueOfShareAndSecurities)
   {
      this.valueOfShareAndSecurities = valueOfShareAndSecurities;
   }

   public java.lang.Integer getFixedDeposits()
   {
      return this.fixedDeposits;
   }

   public void setFixedDeposits(java.lang.Integer fixedDeposits)
   {
      this.fixedDeposits = fixedDeposits;
   }

   public java.lang.Integer getCurrentBalanceInPf()
   {
      return this.currentBalanceInPf;
   }

   public void setCurrentBalanceInPf(java.lang.Integer currentBalanceInPf)
   {
      this.currentBalanceInPf = currentBalanceInPf;
   }

   public java.lang.Integer getOthers()
   {
      return this.others;
   }

   public void setOthers(java.lang.Integer others)
   {
      this.others = others;
   }

   public java.lang.Integer getTotalAssests()
   {
      return this.totalAssests;
   }

   public void setTotalAssests(java.lang.Integer totalAssests)
   {
      this.totalAssests = totalAssests;
   }

   public java.lang.Integer getCreditSocietyLoan()
   {
      return this.creditSocietyLoan;
   }

   public void setCreditSocietyLoan(java.lang.Integer creditSocietyLoan)
   {
      this.creditSocietyLoan = creditSocietyLoan;
   }

   public java.lang.Integer getEmployerLoan()
   {
      return this.employerLoan;
   }

   public void setEmployerLoan(java.lang.Integer employerLoan)
   {
      this.employerLoan = employerLoan;
   }

   public java.lang.Integer getHomeLoan()
   {
      return this.homeLoan;
   }

   public void setHomeLoan(java.lang.Integer homeLoan)
   {
      this.homeLoan = homeLoan;
   }

   public java.lang.Integer getPfLoan()
   {
      return this.pfLoan;
   }

   public void setPfLoan(java.lang.Integer pfLoan)
   {
      this.pfLoan = pfLoan;
   }

   public java.lang.Integer getVehicleLoan()
   {
      return this.vehicleLoan;
   }

   public void setVehicleLoan(java.lang.Integer vehicleLoan)
   {
      this.vehicleLoan = vehicleLoan;
   }

   public java.lang.Integer getPersonalLoan()
   {
      return this.personalLoan;
   }

   public void setPersonalLoan(java.lang.Integer personalLoan)
   {
      this.personalLoan = personalLoan;
   }

   public java.lang.Integer getOtherLoan()
   {
      return this.otherLoan;
   }

   public void setOtherLoan(java.lang.Integer otherLoan)
   {
      this.otherLoan = otherLoan;
   }

   public java.lang.Integer getCreditCard()
   {
      return this.creditCard;
   }

   public void setCreditCard(java.lang.Integer creditCard)
   {
      this.creditCard = creditCard;
   }

   public java.lang.Integer getTotalLiabilites()
   {
      return this.totalLiabilites;
   }

   public void setTotalLiabilites(java.lang.Integer totalLiabilites)
   {
      this.totalLiabilites = totalLiabilites;
   }

   public FinancialDetails(java.lang.Long id, java.lang.Long processInstanceID,
         java.lang.String customerOccupation, java.lang.Integer month1Salary,
         java.lang.Integer month2Salary, java.lang.Integer month3Salary,
         java.lang.Integer monthlyAvgSalary, java.lang.Integer year2Income,
         java.lang.Integer year1Income, java.lang.Integer year3Income,
         java.lang.Integer avgAnnualIncome, java.lang.Integer otherIncome,
         java.lang.Integer existingMonthlyEMI,
         java.lang.Integer incomeCreditScore, java.lang.Integer cashAtBank,
         java.lang.Integer valueOfImmovableProperty,
         java.lang.Integer valueOfShareAndSecurities,
         java.lang.Integer fixedDeposits, java.lang.Integer currentBalanceInPf,
         java.lang.Integer others, java.lang.Integer totalAssests,
         java.lang.Integer creditSocietyLoan, java.lang.Integer employerLoan,
         java.lang.Integer homeLoan, java.lang.Integer pfLoan,
         java.lang.Integer vehicleLoan, java.lang.Integer personalLoan,
         java.lang.Integer otherLoan, java.lang.Integer creditCard,
         java.lang.Integer totalLiabilites)
   {
      this.id = id;
      this.processInstanceID = processInstanceID;
      this.customerOccupation = customerOccupation;
      this.month1Salary = month1Salary;
      this.month2Salary = month2Salary;
      this.month3Salary = month3Salary;
      this.monthlyAvgSalary = monthlyAvgSalary;
      this.year2Income = year2Income;
      this.year1Income = year1Income;
      this.year3Income = year3Income;
      this.avgAnnualIncome = avgAnnualIncome;
      this.otherIncome = otherIncome;
      this.existingMonthlyEMI = existingMonthlyEMI;
      this.incomeCreditScore = incomeCreditScore;
      this.cashAtBank = cashAtBank;
      this.valueOfImmovableProperty = valueOfImmovableProperty;
      this.valueOfShareAndSecurities = valueOfShareAndSecurities;
      this.fixedDeposits = fixedDeposits;
      this.currentBalanceInPf = currentBalanceInPf;
      this.others = others;
      this.totalAssests = totalAssests;
      this.creditSocietyLoan = creditSocietyLoan;
      this.employerLoan = employerLoan;
      this.homeLoan = homeLoan;
      this.pfLoan = pfLoan;
      this.vehicleLoan = vehicleLoan;
      this.personalLoan = personalLoan;
      this.otherLoan = otherLoan;
      this.creditCard = creditCard;
      this.totalLiabilites = totalLiabilites;
   }

}