package page.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class IncidentBasicDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INCIDENTBASICDETAILS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "INCIDENTBASICDETAILS_ID_GENERATOR", sequenceName = "INCIDENTBASICDETAILS_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String incidentNumber;

   private String incidentDate;

   private java.lang.String incidentApplicationType;

   private java.lang.String incidentApplicantStatus;

   private java.lang.String incidentApplicationRelationship;

   private java.lang.Long processInstanceID;

   public IncidentBasicDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getIncidentNumber()
   {
      return this.incidentNumber;
   }

   public void setIncidentNumber(java.lang.String incidentNumber)
   {
      this.incidentNumber = incidentNumber;
   }

   public java.lang.String getIncidentApplicationType()
   {
      return this.incidentApplicationType;
   }

   public void setIncidentApplicationType(
         java.lang.String incidentApplicationType)
   {
      this.incidentApplicationType = incidentApplicationType;
   }

   public java.lang.String getIncidentApplicantStatus()
   {
      return this.incidentApplicantStatus;
   }

   public void setIncidentApplicantStatus(
         java.lang.String incidentApplicantStatus)
   {
      this.incidentApplicantStatus = incidentApplicantStatus;
   }

   public java.lang.String getIncidentApplicationRelationship()
   {
      return this.incidentApplicationRelationship;
   }

   public void setIncidentApplicationRelationship(
         java.lang.String incidentApplicationRelationship)
   {
      this.incidentApplicationRelationship = incidentApplicationRelationship;
   }

   public java.lang.String getIncidentDate()
   {
      return this.incidentDate;
   }

   public void setIncidentDate(java.lang.String incidentDate)
   {
      this.incidentDate = incidentDate;
   }

   public java.lang.Long getProcessInstanceID()
   {
      return this.processInstanceID;
   }

   public void setProcessInstanceID(java.lang.Long processInstanceID)
   {
      this.processInstanceID = processInstanceID;
   }

   public IncidentBasicDetails(java.lang.Long id, java.lang.String incidentNumber,
         java.lang.String incidentDate,
         java.lang.String incidentApplicationType,
         java.lang.String incidentApplicantStatus,
         java.lang.String incidentApplicationRelationship,
         java.lang.Long processInstanceID)
   {
      this.id = id;
      this.incidentNumber = incidentNumber;
      this.incidentDate = incidentDate;
      this.incidentApplicationType = incidentApplicationType;
      this.incidentApplicantStatus = incidentApplicantStatus;
      this.incidentApplicationRelationship = incidentApplicationRelationship;
      this.processInstanceID = processInstanceID;
   }

}