package page.lospoc;

import java.lang.Number;

    rule "ageBelow18"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge < 18.0 )
	then
		customerDetails.setAgeCreditScore( 0 );
	end
	
	rule "ageAbove18AndBelow25"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge >= 18.0 && customerAge < 26.0 )
	then
		customerDetails.setAgeCreditScore( 5 );
	end
	
	rule "ageAbove26AndBelow35"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge >= 26.0 && customerAge < 36.0 )
	then
		customerDetails.setAgeCreditScore( 15 );
	end
	
	rule "ageAbove36AndBelow45"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge >= 36.0 && customerAge < 46.0 )
	then
		customerDetails.setAgeCreditScore( 10 );
	end
	
	rule "ageAbove46AndBelow55"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge >= 46.0 && customerAge < 56.0 )
	then
		customerDetails.setAgeCreditScore( 8 );
	end
	
	rule "ageAbove55"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customerDetails : CustomerDetails( customerAge >= 56.0 )
	then
		customerDetails.setAgeCreditScore( 3 );
	end
	
	rule "monthlySalAbove0Below8000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( monthlyAvgSalary > 0 && monthlyAvgSalary < 8001 )
	then
		financialDetails.setIncomeCreditScore( 3 );
	end
	
	rule "monthlySalAbove8000AndBelow25001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( monthlyAvgSalary >= 8001 && monthlyAvgSalary < 25001 )
	then
		financialDetails.setIncomeCreditScore( 5 );
	end
	
	rule "monthlySalAbove25000AndBelow50001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( monthlyAvgSalary >= 25001 && monthlyAvgSalary < 50001 )
	then
		financialDetails.setIncomeCreditScore( 10 );
	end
	
	rule "monthlySalAbove50000AndBelow100001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( monthlyAvgSalary >= 50001 && monthlyAvgSalary < 100001 )
	then
		financialDetails.setIncomeCreditScore( 15 );
	end
	
	rule "monthlySalAbove100000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( monthlyAvgSalary >= 100001 )
	then
		financialDetails.setIncomeCreditScore( 20 );
    end
	
	rule "incomeAbove0Below8000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( avgAnnualIncome/12 > 0 && avgAnnualIncome/12 < 8001 )
	then
		financialDetails.setIncomeCreditScore( 3 );
	end
	
	rule "incomeAbove8000AndBelow25001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( avgAnnualIncome/12 >= 8001 && avgAnnualIncome/12 < 25001 )
	then
		financialDetails.setIncomeCreditScore( 5 );
	end
	
	rule "incomeAbove25000AndBelow50001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( avgAnnualIncome/12 >= 25001 && avgAnnualIncome/12 < 50001 )
	then
		financialDetails.setIncomeCreditScore( 10 );
	end
	
	rule "incomeAbove50000AndBelow100001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( avgAnnualIncome/12 >= 50001 && avgAnnualIncome/12 < 100001 )
	then
		financialDetails.setIncomeCreditScore( 15 );
	end
	
	rule "incomeAbove100000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		financialDetails : FinancialDetails( avgAnnualIncome/12 >= 100001 )
	then
		financialDetails.setIncomeCreditScore( 20 );
    end