package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BlackListCheckInformation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BLACKLISTCHECKINFORMATION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BLACKLISTCHECKINFORMATION_ID_GENERATOR", sequenceName = "BLACKLISTCHECKINFORMATION_ID_SEQ")
   private java.lang.Long id;

   private java.lang.Long processInstanceID;

   private java.lang.String blackListType1;

   private java.lang.Double blackListAmt1;

   private java.lang.String blackListDesc1;

   private java.lang.String blackListDoc1;

   private java.lang.String blackListType2;

   private java.lang.Double blackListAmt2;

   private java.lang.String blackListDesc2;

   private java.lang.String blackListDoc2;

   private java.lang.String blackListType3;

   private java.lang.Double blackListAmt3;

   private java.lang.String blackListDesc3;

   private java.lang.String blackListDoc3;

   private java.lang.String blackListType4;

   private java.lang.Double blackListAmt4;

   private java.lang.String blackListDesc4;

   private java.lang.String blackListDoc4;

   private java.lang.String blackListType5;

   private java.lang.Double blackListAmt5;

   private java.lang.String blackListDesc5;

   private java.lang.String blackListDoc5;

   private java.lang.String blackListDeviationStatus1;

   private java.lang.String blackListDeviationStatus2;

   private java.lang.String blackListDeviationStatus3;

   private java.lang.String blackListDeviationStatus4;

   private java.lang.String blackListDeviationStatus5;

   private java.lang.String blackListDeviationDesc1;

   private java.lang.String blackListDeviationDesc2;

   private java.lang.String blackListDeviationDesc3;

   private java.lang.String blackListDeviationDesc4;

   private java.lang.String blackListDeviationDesc5;

   public BlackListCheckInformation()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Long getProcessInstanceID()
   {
      return this.processInstanceID;
   }

   public void setProcessInstanceID(java.lang.Long processInstanceID)
   {
      this.processInstanceID = processInstanceID;
   }

   public java.lang.String getBlackListType1()
   {
      return this.blackListType1;
   }

   public void setBlackListType1(java.lang.String blackListType1)
   {
      this.blackListType1 = blackListType1;
   }

   public java.lang.Double getBlackListAmt1()
   {
      return this.blackListAmt1;
   }

   public void setBlackListAmt1(java.lang.Double blackListAmt1)
   {
      this.blackListAmt1 = blackListAmt1;
   }

   public java.lang.String getBlackListDesc1()
   {
      return this.blackListDesc1;
   }

   public void setBlackListDesc1(java.lang.String blackListDesc1)
   {
      this.blackListDesc1 = blackListDesc1;
   }

   public java.lang.String getBlackListDoc1()
   {
      return this.blackListDoc1;
   }

   public void setBlackListDoc1(java.lang.String blackListDoc1)
   {
      this.blackListDoc1 = blackListDoc1;
   }

   public java.lang.String getBlackListType2()
   {
      return this.blackListType2;
   }

   public void setBlackListType2(java.lang.String blackListType2)
   {
      this.blackListType2 = blackListType2;
   }

   public java.lang.Double getBlackListAmt2()
   {
      return this.blackListAmt2;
   }

   public void setBlackListAmt2(java.lang.Double blackListAmt2)
   {
      this.blackListAmt2 = blackListAmt2;
   }

   public java.lang.String getBlackListDesc2()
   {
      return this.blackListDesc2;
   }

   public void setBlackListDesc2(java.lang.String blackListDesc2)
   {
      this.blackListDesc2 = blackListDesc2;
   }

   public java.lang.String getBlackListDoc2()
   {
      return this.blackListDoc2;
   }

   public void setBlackListDoc2(java.lang.String blackListDoc2)
   {
      this.blackListDoc2 = blackListDoc2;
   }

   public java.lang.String getBlackListType3()
   {
      return this.blackListType3;
   }

   public void setBlackListType3(java.lang.String blackListType3)
   {
      this.blackListType3 = blackListType3;
   }

   public java.lang.Double getBlackListAmt3()
   {
      return this.blackListAmt3;
   }

   public void setBlackListAmt3(java.lang.Double blackListAmt3)
   {
      this.blackListAmt3 = blackListAmt3;
   }

   public java.lang.String getBlackListDesc3()
   {
      return this.blackListDesc3;
   }

   public void setBlackListDesc3(java.lang.String blackListDesc3)
   {
      this.blackListDesc3 = blackListDesc3;
   }

   public java.lang.String getBlackListDoc3()
   {
      return this.blackListDoc3;
   }

   public void setBlackListDoc3(java.lang.String blackListDoc3)
   {
      this.blackListDoc3 = blackListDoc3;
   }

   public java.lang.String getBlackListType4()
   {
      return this.blackListType4;
   }

   public void setBlackListType4(java.lang.String blackListType4)
   {
      this.blackListType4 = blackListType4;
   }

   public java.lang.Double getBlackListAmt4()
   {
      return this.blackListAmt4;
   }

   public void setBlackListAmt4(java.lang.Double blackListAmt4)
   {
      this.blackListAmt4 = blackListAmt4;
   }

   public java.lang.String getBlackListDesc4()
   {
      return this.blackListDesc4;
   }

   public void setBlackListDesc4(java.lang.String blackListDesc4)
   {
      this.blackListDesc4 = blackListDesc4;
   }

   public java.lang.String getBlackListDoc4()
   {
      return this.blackListDoc4;
   }

   public void setBlackListDoc4(java.lang.String blackListDoc4)
   {
      this.blackListDoc4 = blackListDoc4;
   }

   public java.lang.String getBlackListType5()
   {
      return this.blackListType5;
   }

   public void setBlackListType5(java.lang.String blackListType5)
   {
      this.blackListType5 = blackListType5;
   }

   public java.lang.Double getBlackListAmt5()
   {
      return this.blackListAmt5;
   }

   public void setBlackListAmt5(java.lang.Double blackListAmt5)
   {
      this.blackListAmt5 = blackListAmt5;
   }

   public java.lang.String getBlackListDesc5()
   {
      return this.blackListDesc5;
   }

   public void setBlackListDesc5(java.lang.String blackListDesc5)
   {
      this.blackListDesc5 = blackListDesc5;
   }

   public java.lang.String getBlackListDoc5()
   {
      return this.blackListDoc5;
   }

   public void setBlackListDoc5(java.lang.String blackListDoc5)
   {
      this.blackListDoc5 = blackListDoc5;
   }

   public java.lang.String getBlackListDeviationStatus1()
   {
      return this.blackListDeviationStatus1;
   }

   public void setBlackListDeviationStatus1(
         java.lang.String blackListDeviationStatus1)
   {
      this.blackListDeviationStatus1 = blackListDeviationStatus1;
   }

   public java.lang.String getBlackListDeviationStatus2()
   {
      return this.blackListDeviationStatus2;
   }

   public void setBlackListDeviationStatus2(
         java.lang.String blackListDeviationStatus2)
   {
      this.blackListDeviationStatus2 = blackListDeviationStatus2;
   }

   public java.lang.String getBlackListDeviationStatus3()
   {
      return this.blackListDeviationStatus3;
   }

   public void setBlackListDeviationStatus3(
         java.lang.String blackListDeviationStatus3)
   {
      this.blackListDeviationStatus3 = blackListDeviationStatus3;
   }

   public java.lang.String getBlackListDeviationStatus4()
   {
      return this.blackListDeviationStatus4;
   }

   public void setBlackListDeviationStatus4(
         java.lang.String blackListDeviationStatus4)
   {
      this.blackListDeviationStatus4 = blackListDeviationStatus4;
   }

   public java.lang.String getBlackListDeviationStatus5()
   {
      return this.blackListDeviationStatus5;
   }

   public void setBlackListDeviationStatus5(
         java.lang.String blackListDeviationStatus5)
   {
      this.blackListDeviationStatus5 = blackListDeviationStatus5;
   }

   public java.lang.String getBlackListDeviationDesc1()
   {
      return this.blackListDeviationDesc1;
   }

   public void setBlackListDeviationDesc1(java.lang.String blackListDeviationDesc1)
   {
      this.blackListDeviationDesc1 = blackListDeviationDesc1;
   }

   public java.lang.String getBlackListDeviationDesc2()
   {
      return this.blackListDeviationDesc2;
   }

   public void setBlackListDeviationDesc2(java.lang.String blackListDeviationDesc2)
   {
      this.blackListDeviationDesc2 = blackListDeviationDesc2;
   }

   public java.lang.String getBlackListDeviationDesc3()
   {
      return this.blackListDeviationDesc3;
   }

   public void setBlackListDeviationDesc3(java.lang.String blackListDeviationDesc3)
   {
      this.blackListDeviationDesc3 = blackListDeviationDesc3;
   }

   public java.lang.String getBlackListDeviationDesc4()
   {
      return this.blackListDeviationDesc4;
   }

   public void setBlackListDeviationDesc4(java.lang.String blackListDeviationDesc4)
   {
      this.blackListDeviationDesc4 = blackListDeviationDesc4;
   }

   public java.lang.String getBlackListDeviationDesc5()
   {
      return this.blackListDeviationDesc5;
   }

   public void setBlackListDeviationDesc5(java.lang.String blackListDeviationDesc5)
   {
      this.blackListDeviationDesc5 = blackListDeviationDesc5;
   }

   public BlackListCheckInformation(java.lang.Long id,
         java.lang.Long processInstanceID, java.lang.String blackListType1,
         java.lang.Double blackListAmt1, java.lang.String blackListDesc1,
         java.lang.String blackListDoc1, java.lang.String blackListType2,
         java.lang.Double blackListAmt2, java.lang.String blackListDesc2,
         java.lang.String blackListDoc2, java.lang.String blackListType3,
         java.lang.Double blackListAmt3, java.lang.String blackListDesc3,
         java.lang.String blackListDoc3, java.lang.String blackListType4,
         java.lang.Double blackListAmt4, java.lang.String blackListDesc4,
         java.lang.String blackListDoc4, java.lang.String blackListType5,
         java.lang.Double blackListAmt5, java.lang.String blackListDesc5,
         java.lang.String blackListDoc5,
         java.lang.String blackListDeviationStatus1,
         java.lang.String blackListDeviationStatus2,
         java.lang.String blackListDeviationStatus3,
         java.lang.String blackListDeviationStatus4,
         java.lang.String blackListDeviationStatus5,
         java.lang.String blackListDeviationDesc1,
         java.lang.String blackListDeviationDesc2,
         java.lang.String blackListDeviationDesc3,
         java.lang.String blackListDeviationDesc4,
         java.lang.String blackListDeviationDesc5)
   {
      this.id = id;
      this.processInstanceID = processInstanceID;
      this.blackListType1 = blackListType1;
      this.blackListAmt1 = blackListAmt1;
      this.blackListDesc1 = blackListDesc1;
      this.blackListDoc1 = blackListDoc1;
      this.blackListType2 = blackListType2;
      this.blackListAmt2 = blackListAmt2;
      this.blackListDesc2 = blackListDesc2;
      this.blackListDoc2 = blackListDoc2;
      this.blackListType3 = blackListType3;
      this.blackListAmt3 = blackListAmt3;
      this.blackListDesc3 = blackListDesc3;
      this.blackListDoc3 = blackListDoc3;
      this.blackListType4 = blackListType4;
      this.blackListAmt4 = blackListAmt4;
      this.blackListDesc4 = blackListDesc4;
      this.blackListDoc4 = blackListDoc4;
      this.blackListType5 = blackListType5;
      this.blackListAmt5 = blackListAmt5;
      this.blackListDesc5 = blackListDesc5;
      this.blackListDoc5 = blackListDoc5;
      this.blackListDeviationStatus1 = blackListDeviationStatus1;
      this.blackListDeviationStatus2 = blackListDeviationStatus2;
      this.blackListDeviationStatus3 = blackListDeviationStatus3;
      this.blackListDeviationStatus4 = blackListDeviationStatus4;
      this.blackListDeviationStatus5 = blackListDeviationStatus5;
      this.blackListDeviationDesc1 = blackListDeviationDesc1;
      this.blackListDeviationDesc2 = blackListDeviationDesc2;
      this.blackListDeviationDesc3 = blackListDeviationDesc3;
      this.blackListDeviationDesc4 = blackListDeviationDesc4;
      this.blackListDeviationDesc5 = blackListDeviationDesc5;
   }

}