package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DeviationCheck implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DEVIATIONCHECK_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DEVIATIONCHECK_ID_SEQ", name = "DEVIATIONCHECK_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Deviation Type")
   private java.lang.String deviationType;

   @org.kie.api.definition.type.Label("Deviation Description")
   private java.lang.String deviationDescription;

   @org.kie.api.definition.type.Label("Manager Description")
   private java.lang.String managerDescription;

   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "Description")
   private java.lang.String description;

   public DeviationCheck()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDeviationType()
   {
      return this.deviationType;
   }

   public void setDeviationType(java.lang.String deviationType)
   {
      this.deviationType = deviationType;
   }

   public java.lang.String getDeviationDescription()
   {
      return this.deviationDescription;
   }

   public void setDeviationDescription(java.lang.String deviationDescription)
   {
      this.deviationDescription = deviationDescription;
   }

   public java.lang.String getManagerDescription()
   {
      return this.managerDescription;
   }

   public void setManagerDescription(java.lang.String managerDescription)
   {
      this.managerDescription = managerDescription;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public DeviationCheck(java.lang.Long id, java.lang.String deviationType,
         java.lang.String deviationDescription,
         java.lang.String managerDescription, java.lang.String status,
         java.lang.String description)
   {
      this.id = id;
      this.deviationType = deviationType;
      this.deviationDescription = deviationDescription;
      this.managerDescription = managerDescription;
      this.status = status;
      this.description = description;
   }

}