package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DeviationCheck implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "DEVIATIONCHECK_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "DEVIATIONCHECK_ID_GENERATOR", sequenceName = "DEVIATIONCHECK_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Deviation Type")
   private java.lang.String deviationType;

   @org.kie.api.definition.type.Label("Deviation Description")
   private java.lang.String deviationDescription;

   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;

   @org.kie.api.definition.type.Label("Officer Description")
   private java.lang.String officerDescription;

   @org.kie.api.definition.type.Label("Approved By")
   private java.lang.String approvedBy;

   private java.lang.Long processInstanceID;

   public DeviationCheck()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDeviationType()
   {
      return this.deviationType;
   }

   public void setDeviationType(java.lang.String deviationType)
   {
      this.deviationType = deviationType;
   }

   public java.lang.String getDeviationDescription()
   {
      return this.deviationDescription;
   }

   public void setDeviationDescription(java.lang.String deviationDescription)
   {
      this.deviationDescription = deviationDescription;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getOfficerDescription()
   {
      return this.officerDescription;
   }

   public void setOfficerDescription(java.lang.String officerDescription)
   {
      this.officerDescription = officerDescription;
   }

   public java.lang.String getApprovedBy()
   {
      return this.approvedBy;
   }

   public void setApprovedBy(java.lang.String approvedBy)
   {
      this.approvedBy = approvedBy;
   }

   public java.lang.Long getProcessInstanceID()
   {
      return this.processInstanceID;
   }

   public void setProcessInstanceID(java.lang.Long processInstanceID)
   {
      this.processInstanceID = processInstanceID;
   }

   public DeviationCheck(java.lang.Long id, java.lang.String deviationType,
         java.lang.String deviationDescription, java.lang.String status,
         java.lang.String description, java.lang.String officerDescription,
         java.lang.String approvedBy, java.lang.Long processInstanceID)
   {
      this.id = id;
      this.deviationType = deviationType;
      this.deviationDescription = deviationDescription;
      this.status = status;
      this.description = description;
      this.officerDescription = officerDescription;
      this.approvedBy = approvedBy;
      this.processInstanceID = processInstanceID;
   }

}