package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Byte documentField;

   public DocumentObject()
   {
   }

   public java.lang.Byte getDocumentField()
   {
      return this.documentField;
   }

   public void setDocumentField(java.lang.Byte documentField)
   {
      this.documentField = documentField;
   }

   public DocumentObject(java.lang.Byte documentField)
   {
      this.documentField = documentField;
   }

}