package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FinancialDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "FINANCIALDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "FINANCIALDETAILS_ID_GENERATOR", sequenceName = "FINANCIALDETAILS_ID_SEQ")
    private java.lang.Long id;

    public FinancialDetails() {
    }
    
    public FinancialDetails(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}