package madhu.lospoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class LoanDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "LOANDETAILS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "LOANDETAILS_ID_GENERATOR", sequenceName = "LOANDETAILS_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Down Payment Amount")
   private java.lang.Double loanDownPaymentAmount;

   @org.kie.api.definition.type.Label(value = "Finance Amount")
   private java.lang.Double loanFinanceAmount;

   @org.kie.api.definition.type.Label(value = "Interest Rate")
   private java.lang.Double loanInterestRate;

   @org.kie.api.definition.type.Label(value = "Interest Rate Type")
   private java.lang.String loanInterestRatetype;

   @org.kie.api.definition.type.Label(value = "Proposed Finance Amount")
   private java.lang.Double loanProposedFinanceAmount;

   @org.kie.api.definition.type.Label(value = "Tenor Months")
   private java.lang.Integer loanTenorMonths;

   @org.kie.api.definition.type.Label(value = "Tenor Years")
   private java.lang.Integer loanTenorYears;

   @org.kie.api.definition.type.Label(value = "Evaluation Price")
   private java.lang.Double loanEvaluationPrice;

   @org.kie.api.definition.type.Label(value = "EMI")
   private java.lang.Double loanEMI;

   public LoanDetails()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Double getLoanDownPaymentAmount()
   {
      return this.loanDownPaymentAmount;
   }

   public void setLoanDownPaymentAmount(java.lang.Double loanDownPaymentAmount)
   {
      this.loanDownPaymentAmount = loanDownPaymentAmount;
   }

   public java.lang.Double getLoanFinanceAmount()
   {
      return this.loanFinanceAmount;
   }

   public void setLoanFinanceAmount(java.lang.Double loanFinanceAmount)
   {
      this.loanFinanceAmount = loanFinanceAmount;
   }

   public java.lang.Double getLoanInterestRate()
   {
      return this.loanInterestRate;
   }

   public void setLoanInterestRate(java.lang.Double loanInterestRate)
   {
      this.loanInterestRate = loanInterestRate;
   }

   public java.lang.String getLoanInterestRatetype()
   {
      return this.loanInterestRatetype;
   }

   public void setLoanInterestRatetype(java.lang.String loanInterestRatetype)
   {
      this.loanInterestRatetype = loanInterestRatetype;
   }

   public java.lang.Double getLoanProposedFinanceAmount()
   {
      return this.loanProposedFinanceAmount;
   }

   public void setLoanProposedFinanceAmount(
         java.lang.Double loanProposedFinanceAmount)
   {
      this.loanProposedFinanceAmount = loanProposedFinanceAmount;
   }

   public java.lang.Integer getLoanTenorMonths()
   {
      return this.loanTenorMonths;
   }

   public void setLoanTenorMonths(java.lang.Integer loanTenorMonths)
   {
      this.loanTenorMonths = loanTenorMonths;
   }

   public java.lang.Integer getLoanTenorYears()
   {
      return this.loanTenorYears;
   }

   public void setLoanTenorYears(java.lang.Integer loanTenorYears)
   {
      this.loanTenorYears = loanTenorYears;
   }

   public java.lang.Double getLoanEvaluationPrice()
   {
      return this.loanEvaluationPrice;
   }

   public void setLoanEvaluationPrice(java.lang.Double loanEvaluationPrice)
   {
      this.loanEvaluationPrice = loanEvaluationPrice;
   }

   public java.lang.Double getLoanEMI()
   {
      return this.loanEMI;
   }

   public void setLoanEMI(java.lang.Double loanEMI)
   {
      this.loanEMI = loanEMI;
   }

   public LoanDetails(java.lang.Long id, java.lang.Double loanDownPaymentAmount,
         java.lang.Double loanFinanceAmount, java.lang.Double loanInterestRate,
         java.lang.String loanInterestRatetype,
         java.lang.Double loanProposedFinanceAmount,
         java.lang.Integer loanTenorMonths, java.lang.Integer loanTenorYears,
         java.lang.Double loanEvaluationPrice, java.lang.Double loanEMI)
   {
      this.id = id;
      this.loanDownPaymentAmount = loanDownPaymentAmount;
      this.loanFinanceAmount = loanFinanceAmount;
      this.loanInterestRate = loanInterestRate;
      this.loanInterestRatetype = loanInterestRatetype;
      this.loanProposedFinanceAmount = loanProposedFinanceAmount;
      this.loanTenorMonths = loanTenorMonths;
      this.loanTenorYears = loanTenorYears;
      this.loanEvaluationPrice = loanEvaluationPrice;
      this.loanEMI = loanEMI;
   }

}