package madhu.lospoc;

import java.lang.Number;

rule "CustomerCreditScoreCalculation"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge < 18 )
		customer : CustomerDetails( customerAge >= 18 && customerAge < 36 )
		customer : CustomerDetails( customerAge >= 36 )
		customer : CustomerDetails( customerMonthlySalary < 10000.0 )
		customer : CustomerDetails( customerMonthlySalary >= 10000.0 && customerMonthlySalary < 30000.0 )
		customer : CustomerDetails( customerMonthlySalary >= 30000.0 )
	then
		customer.setAgeCreditScore( 3.0 );
		customer.setAgeCreditScore( 5.0 );
		customer.setAgeCreditScore( 8.0 );
		customer.setIncomeCreditScore( 3.0 );
		customer.setIncomeCreditScore( 5.0 );
		customer.setIncomeCreditScore( 8.0 );
end