package madhu.lospoc;

import java.lang.Number;

    rule "ageBelow18"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge < 18 )
	then
		customer.setAgeCreditScore( 0.0 );
	end
	
	rule "ageAbove18AndBelow25"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge >= 18 && customerAge < 26 )
	then
		customer.setAgeCreditScore( 5.0 );
	end
	
	rule "ageAbove26AndBelow35"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge >= 26 && customerAge < 36 )
	then
		customer.setAgeCreditScore( 15.0 );
	end
	
	rule "ageAbove36AndBelow45"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge >= 36 && customerAge < 46 )
	then
		customer.setAgeCreditScore( 10.0 );
	end
	
	rule "ageAbove46AndBelow55"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge >= 46 && customerAge < 56 )
	then
		customer.setAgeCreditScore( 8.0 );
	end
	
	rule "ageAbove55"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerAge >= 56 )
	then
		customer.setAgeCreditScore( 3.0 );
	end
	
	rule "incomeBelow8000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerMonthlySalary < 8001.0 )
	then
		customer.setIncomeCreditScore( 3.0 );
	end
	
	rule "incomeAbove8000AndBelow25001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerMonthlySalary >= 8001.0 && customerMonthlySalary < 25001.0 )
	then
		customer.setIncomeCreditScore( 5.0 );
	end
	
	rule "incomeAbove25000AndBelow50001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerMonthlySalary >= 25001.0 && customerMonthlySalary < 50001.0 )
	then
		customer.setIncomeCreditScore( 10.0 );
	end
	
	rule "incomeAbove50000AndBelow100001"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerMonthlySalary >= 50001.0 && customerMonthlySalary < 100001.0 )
	then
		customer.setIncomeCreditScore( 15.0 );
	end
	
	rule "incomeAbove100000"
	dialect "mvel"
	ruleflow-group "CustomerCreditScoreCalculation"
	when
		customer : CustomerDetails( customerMonthlySalary >= 100001.0 )
	then
		customer.setIncomeCreditScore( 20.0 );
    end